@REM -*- coding: windows-1252; mode: bat -*-
@echo off
REM ----------------------------------------------------------------------------
REM --                             --  File:     cdbtools-activate.bat
REM -- Copyright (C) 2017 darmarIT --  Author:   Markus Heiser
REM --     All rights reserved     --  mail:     markus.heiser@darmarIT.de
REM --                             --  http://www.darmarIT.de
REM ----------------------------------------------------------------------------

IF NOT DEFINED CDBTOOLS_HOME (
   echo ERROR: script %~n0 missing CDBTOOLS_HOME environment
   goto Exit
)

REM CDBTools
REM --------

SET CDBTOOLS_ENV=
SET CDBTOOLS_PY27=
SET CDBTOOLS_CACHE=
SET CDBTOOLS_DIST=
SET CDBTOOLS_SW_DOWNLOAD=
SET CDBTOOLS_PIP_DOWNLOAD=

SET "PIP_CONFIG_FILE=%CDBTOOLS_HOME%\bootstrap\pip.config"

REM PROMPT
REM ------

if NOT DEFINED _OLD_CDBTOOLS_PROMPT GOTO DEACTIVATED_PROMPT
    SET "PROMPT=%_OLD_CDBTOOLS_PROMPT%"
    SET _OLD_CDBTOOLS_PROMPT=
:DEACTIVATED_PROMPT

REM PYTHONHOME
REM ----------

IF NOT DEFINED _OLD_CDBTOOLS_PYTHONHOME GOTO DEACTIVATED_HOME
    SET "PYTHONHOME=%_OLD_CDBTOOLS_PYTHONHOME%"
    SET _OLD_CDBTOOLS_PYTHONHOME=
:DEACTIVATED_HOME

REM PATH
REM ------

if NOT DEFINED _OLD_CDBTOOLS_PATH GOTO DEACTIVATED_PATH
    SET "PATH=%_OLD_CDBTOOLS_PATH%"
    SET _OLD_CDBTOOLS_PATH=
:DEACTIVATED_PATH

REM the user scheme
REM ---------------
REM https://docs.python.org/2/install/index.html#inst-alt-install-user

IF NOT DEFINED _OLD_CDBTOOLS_PYTHONUSERBASE GOTO DEACTIVATED_USERBASE
    SET "PYTHONUSERBASE=%_OLD_CDBTOOLS_PYTHONUSERBASE%"
    SET _OLD_CDBTOOLS_PYTHONUSERBASE=
:DEACTIVATED_USERBASE

REM pip config
REM ----------

IF NOT DEFINED _OLD_CDBTOOLS_PIP_CONFIG_FILE GOTO DEACTIVATED_PIP_CONFIG_FILE
    SET "PIP_CONFIG_FILE=%_OLD_CDBTOOLS_PIP_CONFIG_FILE%"
    SET _OLD_CDBTOOLS_PIP_CONFIG_FILE=
:DEACTIVATED_PIP_CONFIG_FILE

REM PYTHONPATH
REM ----------

IF NOT DEFINED _OLD_CDBTOOLS_PYTHONPATH GOTO DEACTIVATED_PYTHONPATH
    set "PYTHONPATH=%_OLD_CDBTOOLS_PYTHONPATH%"
    set _OLD_CDBTOOLS_PYTHONPATH=
:DEACTIVATED_PYTHONPATH
